### ISSUE TITLE
[Bug]: 使用港澳居民来往内地通行证无法抢票

### ISSUE THREAD

**Issue by TaiMiao** [biliticket/BHYG#103]
### 描述这个Bug

选择购票人后报错，报错信息：程序出现错误，错误信息：string index out of range 错误追踪ID：855699f214c84c39aad75a18a6e952ce

### 复现步骤

启动程序
登陆账户
选择项目开票时间定时抢票
选择否
输入85938
选择1. 2024-07-14 周日
选择5. 大会员提前抢-S档 1380.0元
选择两个购票人(大陆身份证+港澳居民来往内地通行证)
出现报错

### 预期操作

不报错，开始抢票

### 截图

![image](https://github.com/biliticket/BHYG/assets/173268238/7f90ed7a-939c-4939-bfdd-bf4094f1450e)

### 问题版本

main分支-Release

### 日志

```shell
ERROR    | 程序出现错误，错误信息：string index out of range 错误追踪ID：855699f214c84c39aad75a18a6e952ce
```

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by TaiMiao** [comment]
使用中国大陆身份证可以正常抢票，可是是用港澳居民来往内地通行证无法正常抢票

**Comment by TaiMiao** [comment]
港澳居民来往内地通行证证件号格式：1个字母+8个数字

**Comment by ZianTT** [comment]
> ```shell
> 855699f214c84c39aad75a18a6e952ce
> ```

问题已知悉，将尽快修复

**Comment by ZianTT** [comment]
6cb6483 修复了问题，在v0.6.3版本可以发布
