### ISSUE TITLE
[Bug]: 账号异常

### ISSUE THREAD

**Issue by Sherlockliu7777** [biliticket/BHYG#120]
### 描述这个Bug

账号异常

### 复现步骤

![image](https://github.com/biliticket/BHYG/assets/120246178/e1dc6298-fe1e-446a-bddc-f0583c81312d)

### 预期操作

![image](https://github.com/biliticket/BHYG/assets/120246178/6b08f273-6efc-456f-b9c2-c7645a5b0dac)

### 截图

![image](https://github.com/biliticket/BHYG/assets/120246178/c868c2bd-5c92-462f-8b50-663cb37c9ec4)

### 问题版本

main分支-Release

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by TaiMiao** [comment]
正常现象，后续更新会修复
