### ISSUE TITLE
[Bug]: BW抢票失败：程序出现错误，错误信息：'token'

### ISSUE THREAD

**Issue by hllyd** [biliticket/BHYG#123]
### 描述这个Bug

程序出现错误，错误信息：'token'

### 复现步骤

BW2024定时抢票失败

订单链接打开是一个空订单，并且PC网页端界面上会触发叔叔的拥挤提示

### 预期操作

定时抢票成功

### 截图

![351afd9d-d4ae-42bb-a721-8f47b34ab6e0](https://github.com/biliticket/BHYG/assets/52808557/571d4fcc-b59f-44e6-8ffe-1e83add7d9c2)
![7541c398-1bd7-412a-9271-a2f958693e50](https://github.com/biliticket/BHYG/assets/52808557/b7666bac-025c-469b-a505-05c12416ef7d)

### 问题版本

main分支-Release

### 日志

```shell
日志见截图
```

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
该问题（token）将在下一个Release修复
准备订单链接不能在其他浏览器打开，仅用于debug
