### ISSUE TITLE
[Bug]: 被412风控

### ISSUE THREAD

**Issue by Sherlockliu7777** [biliticket/BHYG#124]
### 描述这个Bug

被412风控

### 复现步骤

![image](https://github.com/biliticket/BHYG/assets/120246178/7e47d719-2dc4-4f87-8d8e-6648b5143175)

咨询一下，wifi切换成手机热点再切换回来能有用么？

### 预期操作

![image](https://github.com/biliticket/BHYG/assets/120246178/9807b40b-f342-47e3-ad39-d211ce1d3a77)

### 截图

![image](https://github.com/biliticket/BHYG/assets/120246178/7d6a10b4-696c-4d94-8b44-6fbebca45cfe)

### 问题版本

main分支-Release

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
412一般30分钟，30分钟后再试

**Comment by Violiate** [comment]
412风控原因：请求过于频繁

**Comment by Sherlockliu7777** [comment]
多谢， 默认是0.2s， 建议改成多长呢？ 抢余票用

**Comment by ZianTT** [comment]
> 多谢， 默认是0.2s， 建议改成多长呢？ 抢余票用

改大一点吧1啥的，现在很容易被控了
