### ISSUE TITLE
打不开软件

### ISSUE THREAD

**Issue by hetaoawa** [biliticket/BHYG#128]
对，就是打不开软件。。。。
打开程序就闪退
![image](https://github.com/biliticket/BHYG/assets/79517899/92986db8-1bc9-4ec8-89bf-b763f77da7b6)
这是服务器上进程窗口一闪而过的画面，因为太快了截不到，所以只能拍屏了，抱歉 orz......
服务器系统 Winserver 2012 R2 数据中心版
家里的电脑也打不开....
![image](https://github.com/biliticket/BHYG/assets/79517899/ce8fd72b-cc46-45a8-8710-0c9be9444a7b)
系统 Win 7
这个库电脑里应该是有的，我也单放了一份在抢票程序的文件夹下
麻烦大佬看看（磕

**Comment by ZianTT** [comment]
Windows版本不支持，目前支持win10/11

**Comment by hetaoawa** [comment]
Winserver 2012 R2 也支持不到是吗

**Comment by ZianTT** [comment]
> Winserver 2012 R2 也支持不到是吗

同时期的server都不行，群友说2022可以，你试试看

**Comment by xiazeyu** [comment]
2022亲测有效
