### ISSUE TITLE
关于在购票过程中要求填写完整手机号的问题

### ISSUE THREAD

**Issue by Andy1782010** [biliticket/BHYG#136]
作者大大您好！
近日，我朋友在B站会员购购买其他展的过程中，出现了要求填写完整手机号以继续的问题
![image](https://github.com/biliticket/BHYG/assets/78524390/65e54aee-f8eb-4f07-97dc-f0b82dda6570)
我猜测，在本次BW二次开票时也会有此项要求。
在此请问，作者大大可否更新一下程序，以适配抢票中可能出现的此项问题？

**Comment by ZianTT** [comment]
已在0.8.1（9天前）完成适配

**Comment by bilibili-William-Who** [comment]
> 已在0.8.1（9天前）完成适配

Hxd发个安装包吧球球了 想去BW（
