### ISSUE TITLE
一直显示配置失败，重新下了好几遍也没用

### ISSUE THREAD

**Issue by xiaomu829** [biliticket/BHYG#139]
![屏幕截图 2024-07-06 133746](https://github.com/biliticket/BHYG/assets/174854227/cf988b17-a383-4275-b0da-a9889e06d290)

**Comment by xiaomu829** [comment]
有办法处理吗

**Comment by yeahnangua** [comment]
如果开了梯子把梯子关了

**Comment by xiaomu829** [comment]
没开梯子呀

**Comment by xiaomu829** [comment]
之前还能用一更新就这样，很奇怪

**Comment by ZianTT** [comment]
更换网络环境

**Comment by xiaomu829** [comment]
用上流量又换了几个wife了都没啥用

**Comment by ZianTT** [comment]
> 用上流量又换了几个wife了都没啥用
> 

那我也没啥办法…
