### ISSUE TITLE
发生什么事了

### ISSUE THREAD

**Issue by sxdavid** [biliticket/BHYG#140]
大佬怎么了，发生甚么事了_(:з」∠)_

**Comment by ZianTT** [comment]
没发生啥啊

**Comment by sxdavid** [comment]
uwu好哦 
今天想用下尝试一下的来着，结果来看更新发现全变成了启动器
说声感谢大佬这么久的付出，谢谢，辛苦大佬了uwu

**Comment by sxdavid** [comment]
@ZianTT uwu好哦
今天想用下尝试一下的来着，结果来看更新发现全变成了启动器
说声感谢大佬这么久的付出，谢谢，辛苦大佬了uwu（虽然，其实我还只用过一次qwq）

**Comment by ZianTT** [comment]
> @ZianTT uwu好哦 今天想用下尝试一下的来着，结果来看更新发现全变成了启动器 说声感谢大佬这么久的付出，谢谢，辛苦大佬了uwu（虽然，其实我还只用过一次qwq）

……其实……只有一个启动器是障眼法……
