### ISSUE TITLE
[Bug]: User-Agent覆写失效

### ISSUE THREAD

**Issue by blackusagi** [biliticket/BHYG#90]
### 描述这个Bug

User-Agent覆写失效

### 复现步骤

在 `main.py` 的第171行中有从 `load_config()` 返回的 `config` 字典中读取 `user-agent` 字段进而写入请求header的 `"User-Agent"` 字段的功能
但在观察`load_config()`函数后, 发现似乎并没有对 `user-agent` 字段进行写入, 这导致请求的UA仍是默认的, 而默认的UA带有 ` BHYG/0.7.7` 的强特征字段, 这是极其危险的.
此外, 在 [geetest.py](https://github.com/biliticket/BHYG/blob/379db74d13b23b0bb3fa365076182f32f04e9d0b/geetest.py#L43) 中也带有这样的风险UA

### 预期操作

发送请求时不应带有明显的脚本标识性UA

### 问题版本

dev分支

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
问题已知悉，覆写将仅在沿用上次所有配置时生效，将在下版本修复为所有情况生效
另外，geetest.py内包含UA的内容为测试性代码，不会真正使用

**Comment by ZianTT** [comment]
此类问题在后续建议使用Security提交，感谢您的配合

**Comment by ZianTT** [comment]
默认UA将被修改，将改为带有手机客户端特征的UA，感谢您的反馈

**Comment by ZianTT** [comment]
默认UA已在 #89 修改

**Comment by ZianTT** [comment]
Fixed in 827e4b4
