### ISSUE TITLE
[Bug]: >> "[]" is not a valid buyerids.

### ISSUE THREAD

**Issue by BeHappy-NoTZG** [biliticket/BHYG#97]
### 描述这个Bug

选择购买人的时候无论选择哪个都不行

### 复现步骤

所有的都默认，选择购买人

### 预期操作

成功，到下一步

### 截图

>> "[]" is not a valid buyerids.
![QQ截图20240628115205](https://github.com/biliticket/BHYG/assets/67235023/2d00d925-9c53-452d-b300-4a7f58ab0bf3)

### 问题版本

main分支-Release

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by DLmaster361** [comment]
在这个多选框中，用户可以使用键盘的上下键来选择一个选项，然后使用空格键来选中或取消选中这个选项，也可以通过TAB键全选或全不选。用户可以使用回车键来确认他们的选择。

**Comment by ZianTT** [comment]
这是预期行为
