### ISSUE TITLE
2024BW相关信息请求

### ISSUE THREAD

**Issue by DLmaster361** [biliticket/BHYG#98]
### 描述这个Bug

2024BW关闭了网页购票，请问这是否影响到本软件的运行？

### 复现步骤

暂无

### 预期操作

本软件使用的API不依赖网页运行

### 问题版本

main分支-Release

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by ZianTT** [comment]
首先，这不属于bug，请前往discussion
其次，请查阅https://docs.bitf1a5h.eu.org/guide/faq.html#%E7%94%B5%E8%84%91%E7%AB%AF%E8%BF%99%E6%AC%A1%E4%B8%8D%E8%83%BD%E6%8A%A2%E4%BA%86-%E8%84%9A%E6%9C%AC%E8%BF%98%E6%9C%89%E7%94%A8%E5%90%97

**Comment by qyyesa** [comment]
Q.电脑端这次不能抢了，脚本还有用吗
A.叔叔这次限制了抢票客户端，建议你关闭脚本，打开手机哔哩哔哩app抢票即可

**Comment by DLmaster361** [comment]
抱歉，我清楚这不是BUG，但我找不到修改标签的位置。对于由于我不熟悉GitHub操作和项目文档而带来的麻烦，我深感抱歉。谢谢您的帮助。

**Comment by ZianTT** [comment]
> 抱歉，我清楚这不是BUG，但我找不到修改标签的位置。对于由于我不熟悉GitHub操作和项目文档而带来的麻烦，我深感抱歉。谢谢您的帮助。

发送Issue时有明确提示前往Discussion
