### ISSUE TITLE
[Bug]: 选择购票人时出现 [] is not a valid buyerid

### ISSUE THREAD

**Issue by Sherlockliu7777** [biliticket/BHYG#99]
### 描述这个Bug

选择购票人时出现 [] is not a valid buyerid

### 复现步骤

选择购票人时出现 [] is not a valid buyerid

### 预期操作

选择购票人时出现 [] is not a valid buyerid

### 截图

![image](https://github.com/biliticket/BHYG/assets/120246178/36037973-00de-416e-a389-80fe403ca3bf)

### 问题版本

main分支-Release

### 我是最新版本

- [X] 我确认这是该分支的最新版本且这是第一个针对该问题的Issue

**Comment by DLmaster361** [comment]
首先，这是预期行为。
在这个多选框中，用户可以使用键盘的上下键来选择一个选项，然后使用空格键来选中或取消选中这个选项，也可以通过TAB键全选或全不选。用户可以使用回车键来确认他们的选择。
最后，希望暂时不要close或加入文档，这玩意已经开了两个Issues...

**Comment by Sherlockliu7777** [comment]
原来是空格选中啊，没注意到，多谢！

**Comment by ZianTT** [comment]
> 首先，这是预期行为。 在这个多选框中，用户可以使用键盘的上下键来选择一个选项，然后使用空格键来选中或取消选中这个选项，也可以通过TAB键全选或全不选。用户可以使用回车键来确认他们的选择。 最后，希望暂时不要close或加入文档，这玩意已经开了两个Issues...

文档加了，没人看。
